#!/bin/bash
source replace_url
url_arr=(
"url = https://github.com/davidhalter/typeshed"
"url= https://github.com/davidhalter/typesfsfshed"
"url=https://github.com/davidhdsfsdfalter/typesfsfshed"
"url=https://github.com/davidhd/type.git"
"   url  =    https://github.com/davidhd/type"
"url = https://github.com/davidhalter/typeshed.git"
# 这个应该不会被替换，没有以url开头
"https://github.com/davidhd/type.git"
"https://github.com/davidhd/type"
)

for url in "${url_arr[@]}"; do
	result=$(replace_url "$url")
	echo "before: $url"
	echo "after: $result"
done

# url in cmake
cmake_urls=(
       "GIT_REPOSITORY https://github.com/google/googletest"
       "GIT_REPOSITORY   https://github.com/google/benchmark"
       "GIT_REPOSITORY            https://github.com/abseil/abseil-cpp"
)
for url in "${cmake_urls[@]}"; do
	result=$(replace_url2 "$url")
	echo "before: $url"
	echo "after: $result"
done




echo "========================================"
cp backup/* .

gitmodule_files=(
	"gitmodule1"
	"gitmodule2"
	"gitmodule3"
)

for file in "${gitmodule_files[@]}";do
	echo "current file $file"
	echo "before:--------------"
	cat "$file"

	replace_url_in_file "$file"
	if [ $? -ne 0 ]; then
		echo "failed in $file"
	fi
	echo "after:--------------"
	cat "$file"
done
# cmake file test
cmake_files=(
	"CMakeLists1"
	"CMakeLists2"
	"CMakeLists3"
)

for file in "${cmake_files[@]}";do
	echo "current file $file"
	echo "before:--------------"
	grep "GIT_REPOSITORY" "$file"

	replace_url_in_file2 "$file"
	if [ $? -ne 0 ]; then
		echo "failed in $file"
	fi
	echo "after:--------------"
	grep "GIT_REPOSITORY" "$file"
done

rm gitmodule*
rm CMakeLists*
